=head1 Simple web app for table maintenance

This web application provides a simple UI for adding, changing and deleting the rows of a table persistently. The essential idea is to use the HTML table itself to manage the changes (the "after image") that have to be sent to the server when the user hits "save".  

It consists of a single web page C<konto.html>, enriched with some JavaScript code in C<konto.js>. Communication with the server is per Ajax, calling a CGI script C<konto.pl> which makes the changes persistent using a class C<CsvTableMaintainer.pm>. The data transfer format in both directions is JSON, which is parsed by Prototype on the client, and by an own package C<MiniJSON.pm> on the server.

See http://ruediger-plantiko.net/konto/ for the running example.

